runtime: nodejs20
instance_class: F2  # Optional: Customize the instance class if needed

env_variables:
  NODE_ENV: 'production'
  NEXT_PUBLIC_SUPABASE_URL: 'SUPABASE_URL_PLACEHOLDER'
  NEXT_PUBLIC_SUPABASE_ANON_KEY: 'SUPABASE_ANON_KEY_PLACEHOLDER'

# Ensure the app serves on port 8080
handlers:
  - url: /.*
    script: auto
    secure: always

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
